#!/bin/bash
merge_template () {
    # Merge template files and do variable substitution
    #
    # $1: Template file
    #
    # Supported directives:
    #   #include filename : Include filename and process it.
    #   ${variable}       : substituted by the value of the variable.
    #
    [ -z "$1" ] && return
    set -f
    while IFS='' read -r line; do
        if [[ "$line" =~ \#include\ (.*) ]]; then
            $FUNCNAME ${BASH_REMATCH[1]}
        else
            while [[ "$line" =~ (\$\{[a-zA-Z_][a-zA-Z_0-9]*\}) ]] ; do
                LHS="${BASH_REMATCH[1]}"
                RHS="$(eval echo "\"$LHS\"")"
                line="${line//$LHS/$RHS}"
            done
            printf "%s\n" "$line"
        fi
    done<$1
    set +f
}
merge_template $1
